### Title of the PR
- [ ] Have you renamed the PR title clearly?  
<!-- Use keywords like: fix, feat, docs, refactor, etc. -->

### Related Issue
Closes: #<issue number>

### Description
<!-- Briefly describe what was changed and why. -->

### Type of Change
- [ ] Bug fix
- [ ] New feature
- [ ] Code style update
- [ ] Breaking change
- [ ] Documentation update

### Affected Areas
- [ ] Code
- [ ] Documentation

### How Has This Been Tested?
<!-- Briefly describe how you tested your changes. -->

### Checklist
- [ ] My code follows the project's style.
- [ ] I have commented where necessary.
- [ ] No new warnings or errors.
- [ ] I have updated the documentation (if needed).

### Additional Notes (optional)
